---
extends: relaxed

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    min-spaces-from-content: 1
  trailing-spaces: enable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  key-duplicates: enable
  empty-lines:
    max: 2
